services:
  web:
    build: .
    container_name: ibm_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER:
      SMTP_PASS:
    restart: always
    networks:
      - webnet
networks:
  webnet:
    external: true

